softeerbootcamp/Team8_FullStack

Backend/build.gradle
Backend/src/main/java/site/devroad/softeer/exceptions/ExceptionType.java
Backend/src/main/java/site/devroad/softeer/src/user/UserController.java
Backend/src/main/java/site/devroad/softeer/src/user/UserRepo.java
Backend/src/main/java/site/devroad/softeer/src/user/UserService.java
Backend/src/main/java/site/devroad/softeer/src/user/dto/PostSignInReq.java
Backend/src/main/java/site/devroad/softeer/src/user/dto/PostSignInRes.java
Backend/src/main/java/site/devroad/softeer/src/user/dto/PostSignUpReq.java
Backend/src/main/java/site/devroad/softeer/src/user/dto/PostSignUpRes.java
Backend/src/main/java/site/devroad/softeer/src/user/model/Account.java
Backend/src/main/java/site/devroad/softeer/src/user/model/LoginInfo.java
Backend/src/test/java/site/devroad/softeer/src/user/UserRepoTest.java
Backend/src/test/java/site/devroad/softeer/src/user/UserServiceTest.java

회원가입 api 구현 완료
signup request의 파라미터가 비어있는지, 혹은 중복된 이메일이 존재하는지를 확인하고 문제가 없다면 회원가입 진행

issue#8 회원가입 api(/api/user/signup) 구현 완료

---

Backend/src/main/java/site/devroad/softeer/exceptions/ExceptionType.java
Backend/src/main/java/site/devroad/softeer/src/user/UserController.java
Backend/src/main/java/site/devroad/softeer/src/user/UserRepo.java
Backend/src/main/java/site/devroad/softeer/src/user/UserService.java
Backend/src/main/java/site/devroad/softeer/src/user/dto/PostSignUpReq.java
Backend/src/main/java/site/devroad/softeer/src/user/model/LoginInfo.java
Backend/src/test/java/site/devroad/softeer/src/user/UserServiceTest.java

- 회원가입 시 중복된 이메일과 휴대폰 번호가 db에 존재하는지 확인
- 중복된 휴대번호가 존재할 때 발생하는 custom exception 추가
- 회원가입의 성공/실패에 대한 테스트코드 작성, 실패는 중복된 이메일과 휴대번호가 존재한다면 적절한 exception이 발생하는지 확인.
- 기존의 UserController에서 체크하던 이메일 중복을 UserService에서 진행하는 것으로 변경함.
- BDD 방식으로 테스트 코드를 작성하려고 노력함.
- 롬복을 제거한 후에도 정상적으로 작동하는지 확인하기 위해 테스트코드를 먼저 작성함.
- 테스트 코드에 유저를 생성하고 삭제하는 과정을 이후에 리팩토링하면 좋을 듯.

issue #19 로그인 api 만들기 진행 중

---

Backend/src/main/java/site/devroad/softeer/src/course/CourseRepo.java
Backend/src/main/java/site/devroad/softeer/src/course/model/Chapter.java
Backend/src/main/java/site/devroad/softeer/src/course/model/Course.java
Backend/src/main/java/site/devroad/softeer/src/course/model/Subject.java
Backend/src/main/java/site/devroad/softeer/src/lecture/model/Course.java
Backend/src/main/java/site/devroad/softeer/src/lecture/model/Subject.java

Subject - Course - Chapter에 해당하는 모델 제작.
/src/~/Course/model 내에 3개를 구현함.

issue #6 모델 만들기

---

Backend/src/main/java/site/devroad/softeer/src/user/dto/PostSignInRes.java
Backend/src/main/java/site/devroad/softeer/src/user/dto/PostSignUpRes.java

getter가 response 객체에 존재하지 않아서 생긴 문제 해결

fix : 406 error fix

---

Backend/src/main/java/site/devroad/softeer/exceptions/CustomException.java
Backend/src/main/java/site/devroad/softeer/exceptions/ExceptionType.java
Backend/src/main/java/site/devroad/softeer/src/course/CourseRepo.java
Backend/src/main/java/site/devroad/softeer/src/course/model/Course.java
Backend/src/main/java/site/devroad/softeer/src/roadmap/RoadmapController.java
Backend/src/main/java/site/devroad/softeer/src/roadmap/RoadmapRepo.java
Backend/src/main/java/site/devroad/softeer/src/roadmap/RoadmapService.java
Backend/src/main/java/site/devroad/softeer/src/roadmap/dto/GetRoadmapRes.java
Backend/src/main/java/site/devroad/softeer/src/roadmap/model/Roadmap.java
Backend/src/main/java/site/devroad/softeer/src/user/UserController.java
Backend/src/main/java/site/devroad/softeer/src/user/UserService.java
Backend/src/main/java/site/devroad/softeer/src/user/dto/PostSignInRes.java
Backend/src/main/java/site/devroad/softeer/src/user/dto/PostSignUpRes.java
Backend/src/test/java/site/devroad/softeer/src/user/UserRepoTest.java

- sign in과 sign up 관련 response 수정
- roadmap repo, service, controller 기본 구현

#40 roadmap api 구현중

---

Backend/build.gradle
Backend/src/main/java/site/devroad/softeer/config/CorsConfig.java
Backend/src/main/java/site/devroad/softeer/exceptions/ExceptionType.java
Backend/src/main/java/site/devroad/softeer/src/user/UserController.java
Backend/src/main/java/site/devroad/softeer/src/user/UserService.java
Backend/src/main/java/site/devroad/softeer/src/user/model/LoginInfo.java
Backend/src/main/java/site/devroad/softeer/utility/CustomRes.java
Backend/src/main/java/site/devroad/softeer/utility/JwtUtility.java
Backend/src/test/java/site/devroad/softeer/utility/JwtUtilityTest.java

JWTUtility 추가

---

Backend/src/main/java/site/devroad/softeer/src/course/model/Chapter.java
Backend/src/main/java/site/devroad/softeer/src/course/repository/ChapterRepo.java
Backend/src/main/java/site/devroad/softeer/src/course/service/CourseService.java
Backend/src/main/java/site/devroad/softeer/src/roadmap/RoadmapController.java
Backend/src/main/java/site/devroad/softeer/src/roadmap/RoadmapService.java
Backend/src/main/java/site/devroad/softeer/src/roadmap/dto/GetCourseDetailRes.java
Backend/src/main/java/site/devroad/softeer/src/roadmap/dto/subdto/ChapterDetail.java

#71 구현 중 
- course id에 해당하는 chapter들의 정보를 리턴해주는 api를 구현함
- chapter의 sequence 순서대로 반환함
- 각 chapter의 완료 여부를 확인하는 방법 필요

issue # 71 course detail api 구현 중

---

Backend/src/main/java/site/devroad/softeer/src/course/service/CourseService.java
Backend/src/main/java/site/devroad/softeer/src/roadmap/RoadmapController.java
Backend/src/main/java/site/devroad/softeer/src/roadmap/dto/GetChapterDetailRes.java
Backend/src/main/java/site/devroad/softeer/src/user/UserController.java
Backend/src/main/java/site/devroad/softeer/src/user/UserService.java
Backend/src/main/java/site/devroad/softeer/utility/JwtUtility.java
Backend/src/test/java/site/devroad/softeer/src/test/TestServiceTest.java
Backend/src/test/java/site/devroad/softeer/src/user/UserServiceTest.java
Backend/src/test/java/site/devroad/softeer/utility/JwtUtilityTest.java

- chapter detail page를 구현하기 위한 get /api/chapter 구현 
- 오류가 발생했던 테스트코드 수정
- yml 파일에 jwt secret key를 넣는 방식으로 수정

chapter detail api 구현 및 테스트코드 오류 수정

---

Backend/src/main/java/site/devroad/softeer/exceptions/ExceptionType.java
Backend/src/main/java/site/devroad/softeer/src/user/UserController.java
Backend/src/main/java/site/devroad/softeer/src/user/UserRepo.java
Backend/src/main/java/site/devroad/softeer/src/user/UserService.java
Backend/src/main/java/site/devroad/softeer/src/user/dto/GetNoUserRes.java
Backend/src/main/java/site/devroad/softeer/src/user/model/LoginInfo.java

no roadmap user api 구현 완료

---

Backend/src/main/java/site/devroad/softeer/src/user/UserRepo.java

noRoadmap 관련 join sql 수정

---

Backend/src/main/java/site/devroad/softeer/src/exam/ExamController.java
Backend/src/main/java/site/devroad/softeer/src/exam/ExamRepo.java
Backend/src/main/java/site/devroad/softeer/src/exam/ExamService.java
Backend/src/main/java/site/devroad/softeer/src/exam/dto/GetExamDetailRes.java
Backend/src/main/java/site/devroad/softeer/src/exam/dto/subdto/ExamDetail.java

Exam 구매 및 상세정보 관련 api 구현

---

Backend/src/main/java/site/devroad/softeer/exceptions/ExceptionType.java
Backend/src/main/java/site/devroad/softeer/src/course/model/Chapter.java
Backend/src/main/java/site/devroad/softeer/src/course/model/Course.java
Backend/src/main/java/site/devroad/softeer/src/course/model/Subject.java
Backend/src/main/java/site/devroad/softeer/src/course/repository/ChapterRepo.java
Backend/src/main/java/site/devroad/softeer/src/course/repository/CourseRepo.java
Backend/src/main/java/site/devroad/softeer/src/course/repository/SubjectRepo.java
Backend/src/main/java/site/devroad/softeer/src/exam/ExamRepo.java
Backend/src/main/java/site/devroad/softeer/src/exam/ExamService.java
Backend/src/main/java/site/devroad/softeer/src/exam/ExamSubmissionRepo.java
Backend/src/main/java/site/devroad/softeer/src/exam/dto/subdto/ExamDetail.java
Backend/src/main/java/site/devroad/softeer/src/exam/model/Exam.java
Backend/src/main/java/site/devroad/softeer/src/exam/model/ExamSubmission.java
Backend/src/main/java/site/devroad/softeer/src/exam/model/SubmissionType.java
Backend/src/main/java/site/devroad/softeer/src/roadmap/dto/subdto/ChapterDetail.java
Backend/src/main/java/site/devroad/softeer/src/roadmap/dto/subdto/CourseDetail.java
Backend/src/main/resources/logback.xml
Backend/src/test/java/site/devroad/softeer/src/test/ExamServiceTest.java
Backend/src/test/java/site/devroad/softeer/src/user/UserServiceTest.java

- Test 테이블 명을 Exam으로 변경
- 예약어 explain을 description으로 변경
- 관련된 변수명, 함수명을 변경함
- 작성해놓은 테스트코드를 확인하며 리팩토링을 진행하여 오류가 발생하는 부분을 수정함.

issue#114 DB 예약어 변경

---

Backend/src/main/java/site/devroad/softeer/src/course/repository/ChapterRepo.java
Backend/src/main/java/site/devroad/softeer/src/course/service/CourseService.java
Backend/src/main/java/site/devroad/softeer/src/exam/ExamRepo.java
Backend/src/main/java/site/devroad/softeer/src/exam/ExamService.java
Backend/src/main/java/site/devroad/softeer/src/exam/dto/subdto/ExamDetail.java
Backend/src/main/java/site/devroad/softeer/src/roadmap/RoadmapController.java
Backend/src/main/java/site/devroad/softeer/src/roadmap/dto/GetChapterDetailRes.java
Backend/src/main/java/site/devroad/softeer/src/roadmap/dto/subdto/ChapterDetail.java

Revert "Refactor/be/user detail"

---

Frontend/fe_vue/src/components/login.vue
Frontend/fe_vue/src/components/signup.vue
Frontend/fe_vue/src/main.js
Frontend/fe_vue/src/view/home.vue

[Fe] 디자인 버그 수정

---

Backend/src/main/java/site/devroad/softeer/exceptions/ExceptionType.java
Backend/src/main/java/site/devroad/softeer/src/exam/ExamController.java
Backend/src/main/java/site/devroad/softeer/src/exam/ExamRepo.java
Backend/src/main/java/site/devroad/softeer/src/exam/ExamService.java
Backend/src/main/java/site/devroad/softeer/src/exam/ExamSubmissionRepo.java
Backend/src/main/java/site/devroad/softeer/src/exam/dto/GetExamDetailRes.java
Backend/src/main/java/site/devroad/softeer/src/exam/dto/domain/ExamDetail.java
Backend/src/main/java/site/devroad/softeer/src/roadmap/RoadmapController.java
Backend/src/main/java/site/devroad/softeer/src/roadmap/RoadmapRepo.java
Backend/src/main/java/site/devroad/softeer/src/roadmap/chapter/ChapterRepo.java
Backend/src/main/java/site/devroad/softeer/src/roadmap/chapter/ChapterService.java
Backend/src/main/java/site/devroad/softeer/src/roadmap/completedchapter/CompletedChapter.java
Backend/src/main/java/site/devroad/softeer/src/roadmap/completedchapter/CompletedChapterRepo.java
Backend/src/main/java/site/devroad/softeer/src/roadmap/course/CourseRepo.java
Backend/src/main/java/site/devroad/softeer/src/roadmap/course/CourseService.java
Backend/src/main/java/site/devroad/softeer/src/roadmap/dto/GetChapterDetailRes.java
Backend/src/main/java/site/devroad/softeer/src/roadmap/dto/GetCourseDetailRes.java
Backend/src/main/java/site/devroad/softeer/src/roadmap/dto/GetSubjectDetailRes.java
Backend/src/main/java/site/devroad/softeer/src/roadmap/dto/domain/ChapterDetail.java
Backend/src/main/java/site/devroad/softeer/src/roadmap/dto/domain/CourseDetail.java
Backend/src/main/java/site/devroad/softeer/src/roadmap/dto/domain/SubjectDetail.java
Backend/src/main/java/site/devroad/softeer/src/roadmap/subject/SubjectRepo.java
Backend/src/main/java/site/devroad/softeer/src/roadmap/subject/SubjectService.java
Backend/src/main/java/site/devroad/softeer/src/roadmap/subject/SubjectToRoadmapRepo.java
Backend/src/main/java/site/devroad/softeer/src/user/UserController.java
Backend/src/main/java/site/devroad/softeer/src/user/UserRepo.java
Backend/src/main/java/site/devroad/softeer/src/user/UserService.java
Backend/src/main/java/site/devroad/softeer/src/user/dto/GetUserDetailRes.java

#144 완료
- user detail api  구현 완료
- chapter finish가 put 될 때 completed chapter에 row 추가함
- 로드맵에 속한 subject의 개수 받아오는 메서드 구현
- exam submission을 통해 현재 subject의 index를 받아옴
- 로드맵에서 최근 챕터의 chapter Id를 받아온 후 이 값을 이용하여 course를 찾고, course의 전체 chapter 수와, 완료된 chapter의 수를 확인하여 course 진행률을 반환해줌
- subscribe 여부를 확인하고 user detail에 넣어줘야함

[BE] issue #144 user detail api 구현 완료

---

Backend/src/main/java/site/devroad/softeer/src/exam/ExamRepo.java
Backend/src/main/java/site/devroad/softeer/src/exam/ExamService.java

-  subscribe null 관련 디버깅
- chapterId가 null 일 때 db Exception 핸들링

[BE] user detail 관련 debug 삭제

---

Backend/src/main/java/site/devroad/softeer/src/exam/ExamRepo.java
Backend/src/main/java/site/devroad/softeer/src/exam/ExamService.java
Backend/src/main/java/site/devroad/softeer/src/exam/dto/domain/ExamDetail.java
Backend/src/main/java/site/devroad/softeer/src/exam/dto/domain/MultiChoiceQuestion.java
Backend/src/main/java/site/devroad/softeer/src/exam/model/ExamMcq.java
Backend/src/main/java/site/devroad/softeer/src/roadmap/RoadmapController.java

- 객관식 시험지가 생겨, 해당 데이터를 정상적으로 가져올 수 있도록 수정함 
- FRQ의 경우 ans와 객관식 문제에 대한 데이터가 null로 넘어가도록 구현함

[BE]  mcq type의 exam detail도 받아올 수 있도록 수정

---

Backend/src/main/java/site/devroad/softeer/src/exam/ExamController.java
Backend/src/main/java/site/devroad/softeer/src/exam/ExamService.java
Backend/src/main/java/site/devroad/softeer/src/exam/ExamSubmissionRepo.java
Backend/src/main/java/site/devroad/softeer/src/exam/dto/PutExamDetailReq.java
Backend/src/main/java/site/devroad/softeer/src/exam/dto/PutExamDetailRes.java
Backend/src/main/java/site/devroad/softeer/src/exam/model/SubmissionType.java
Backend/src/main/java/site/devroad/softeer/src/roadmap/RoadmapController.java
Backend/src/main/java/site/devroad/softeer/src/roadmap/dto/GetSubjectDetailRes.java
Backend/src/main/java/site/devroad/softeer/src/roadmap/dto/domain/CourseDetail.java
Backend/src/main/java/site/devroad/softeer/src/roadmap/subject/SubjectService.java

- 시험 성공/실패 결과를 확인하고 DB에 저장하는 put /api/exam/result을 구현함

[BE] exam result 제출 api 구현

---

Backend/src/main/java/site/devroad/softeer/config/AuthInterceptor.java
Backend/src/main/java/site/devroad/softeer/exceptions/ExceptionType.java
Backend/src/main/java/site/devroad/softeer/src/exam/ExamController.java
Backend/src/main/java/site/devroad/softeer/src/exam/ExamService.java
Backend/src/main/java/site/devroad/softeer/src/exam/ExamSubmissionRepo.java
Backend/src/main/java/site/devroad/softeer/src/exam/dto/GetAssignmentDetail.java
Backend/src/main/java/site/devroad/softeer/src/exam/dto/domain/Assignment.java
Backend/src/main/java/site/devroad/softeer/utility/JwtUtility.java

- assignment detail을 받아오는 api를 구현함
- jwtUtility에서 username을 받는 메서드 구현

[BE] #195 assignment detail 받아오는 api 구현

---

Backend/src/main/java/site/devroad/softeer/src/exam/ExamController.java
Backend/src/main/java/site/devroad/softeer/src/exam/ExamService.java
Backend/src/main/java/site/devroad/softeer/src/exam/dto/GetPeerDetail.java
Backend/src/main/java/site/devroad/softeer/src/exam/dto/domain/PeerDetail.java
Backend/src/main/java/site/devroad/softeer/src/user/UserRepo.java

##What 
1. api : peer detail 구현.
2. 프론트에서 리뷰가 가능한 peer 두명을 보여 줄 수 있게 요청하는 부분을 구현

feat : peer review 기능의 같은 시험을 본 수강생 두명의 정보를 받아오는 기능 구현.

---

Backend/src/main/java/site/devroad/softeer/utility/GithubUtility.java

github issue에 달때 ref=master도 처리가 되도록 수정.

fix : remove ?ref=master if exist

---

Backend/src/main/java/site/devroad/softeer/config/SpringConfig.java
Backend/src/main/java/site/devroad/softeer/src/exam/ExamService.java
Backend/src/main/java/site/devroad/softeer/src/roadmap/RoadmapService.java
Backend/src/main/java/site/devroad/softeer/src/user/UserController.java
Backend/src/main/java/site/devroad/softeer/src/user/UserRepo.java
Backend/src/main/java/site/devroad/softeer/src/user/UserService.java
Backend/src/main/java/site/devroad/softeer/src/user/dto/GetAllUserRes.java
Backend/src/main/java/site/devroad/softeer/src/user/dto/GetNoUserRes.java
Backend/src/test/java/site/devroad/softeer/src/user/UserControllerTest.java
Backend/src/test/java/site/devroad/softeer/src/user/UserServiceTest.java

- mockMVC를 이용하여 User Controller 테스트 코드 작성
- mockito를 이용해 user service 테스트 코드 작성

[BE] User controller, service 테스트 코드 작성

---

Backend/src/main/java/site/devroad/softeer/src/roadmap/course/CourseService.java

completed chatper의 개수를 가져오는 부분에 id 값이 잘못 들어간 부분을 수정함

[BE] fix : completed chapters 가져오는 부분 수정

---

Backend/build.gradle
Backend/src/main/java/site/devroad/softeer/src/roadmap/RoadmapController.java
Backend/src/main/java/site/devroad/softeer/src/roadmap/RoadmapService.java
Backend/src/main/java/site/devroad/softeer/src/roadmap/course/Course.java
Backend/src/main/java/site/devroad/softeer/src/roadmap/course/CourseService.java
Backend/src/main/java/site/devroad/softeer/src/roadmap/subject/SubjectService.java
Backend/src/test/java/site/devroad/softeer/src/exam/ExamServiceTest.java
Backend/src/test/java/site/devroad/softeer/src/roadmap/RoadmapControllerTest.java
Backend/src/test/java/site/devroad/softeer/src/roadmap/RoadmapRepoTest.java
Backend/src/test/java/site/devroad/softeer/src/roadmap/RoadmapServiceTest.java

- 로드맵 컨트롤러 테스트 코드 작성
- test coverage를 확인할 수 있도록 build.gradle 변경

[BE] 로드맵 컨트롤러 테스트 작성, 테스트 커버리지 설정

---

Backend/src/main/java/site/devroad/softeer/src/exam/ExamController.java
Backend/src/main/java/site/devroad/softeer/src/exam/ExamService.java
Backend/src/main/java/site/devroad/softeer/src/user/UserRepo.java

- 피어 리뷰에서 본인을 제외하고 보내도록 accountId를 조건에 추가함

[BE] 피어 리뷰를 추천해줄 때 본인을 제외하도록 sql을 수정
